blog/blog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('homepage.urls')),
    path('bookmark/', include('bookmark.urls')),
    path('practice/', include('blog2.urls')),
]

blog/blog2/urls.py
from .views import *
from django.urls import path


app_name = 'blog2'
urlpatterns = [

    # Example: /
    path('', PostLV.as_view(), name="index"),

    # Example: /post/ (Same as /)
    path('post/', PostLV.as_view(), name='post_list'),

    # Example: /post/django-example/
    path('post/<slug:slug>/', PostDV.as_view(), name='post_detail'),

    # Example: /archive/
    path('archive/', PostAV.as_view(), name='post_archive'),

    # Example: /2012/
    path('<int:year>/', PostYAV.as_view(), name='post_year_archive'),

    # Example: /2012/nov/
    path('<int:year>/<str:month>/', PostMAV.as_view(), name='post_month_archive'),

    # Example: /2012/nov/10
    path('<int:year>/<str:month>/<int:day>/', PostDAV.as_view(), name='post_day_archive'),

    # Example: /today/
    path('today/', PostTAV.as_view(), name='post_today_archive'),
]

blog/bookmark/urls.py
from django.urls import path
from .views import *

from .models import Bookmark as bm

urlpatterns =[
    path('', BookmarkLV.as_view(), name='index'),
    path('<int:pk>/', BookmarkDV.as_view(), name='detail'),
]

blog/homepage/urls.py
from django.urls import path
from . import views

app_name = 'homepage'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('post/<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('post/', views.check_boardnum, name='check_num'),

]

blog/blog2/models.py
from django.db import models
from django.shortcuts import reverse

# Create your models here.

class Post(models.Model):
    title = models.CharField('TITLE', max_length=50)
    slug = models.SlugField('SLUG', unique=True, allow_unicode=True,
                            help_text='one word for title alias')
    description = models.CharField('DESCRIPTION', max_length=100, blank=True,
                                   help_text='simple description txt')
    content = models.TextField('CONTENT')
    create_date = models.DateTimeField('Create Date', auto_now_add=True)
    modify_date = models.DateTimeField('Modify Date', auto_now=True)

    class Meta:
        verbose_name = "post"
        verbose_name_plural = "posts"
        db_table = 'my_post'
        ordering = ('-modify_date',)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog2:post_detail', args=(self.slug,))

    def get_previous_post(self):
        return self.get_previous_in_order()

    def get_next_post(self):
        return self.get_next_in_order()

# help_text란 해당 컬럼을 설명해주는 문구이며, 폼 화면에 나타남. Admin에서 확인가능
# get_next/previous_in_order-> 기준값의 전/다음 post 반환

blog/bookmark/models.py
from django.db import models

# Create your models here.

class Bookmark(models.Model):
    title = models.CharField('book_title', max_length=100, blank=True, null=True)
    url = models.URLField('url', unique=True)

    def __str__(self):
        return self.title

blog/homepage/models.py
from django.db import models as md
from django.utils import timezone as tz
from django.shortcuts import reverse


# Create your models here.

class Board(md.Model):
    title = md.CharField(max_length=200)
    description = md.CharField('DESCRIPTION', max_length=100, blank=True,
                                   help_text='simple description txt')
    text = md.TextField("CONTENT")
    create_date = md.DateTimeField('Create Date', auto_now_add=True)
    modify_date = md.DateTimeField('Modify Date', auto_now=True)
    # 괄호안에 들어가는 문자열(예로들면 published titme)은 레이블이라고 하며
    # 폼 화면에 나타나는 문구이고, admin 사이트에서 확인 가능

    class Meta:
        db_table = 'homepage'
        ordering = ('-create_date',)

    def __str__(self):
        return self.title

    def publish(self):
        self.published_date = tz.now()
        self.save()

    def get_absolute_url(self):
        return reverse('homepage:detail', args=(self.id,))

    def get_previous_post(self):
        return self.get_previous_in_order()

    def get_next_post(self):
        return self.get_next_in_order()

blog/blog2/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from django.views.generic.dates import ArchiveIndexView, YearArchiveView, MonthArchiveView
from django.views.generic.dates import DayArchiveView, TodayArchiveView


from .models import Post


# Create your views here.


# --- ListView
class PostLV(ListView):
    model = Post
    template_name = 'blog2/post_all.html'
    context_object_name = 'posts'
    paginate_by = 2


# -- DetailView
class PostDV(DetailView):
    model = Post


# -- Archiveview
class PostAV(ArchiveIndexView):
    model = Post
    date_field = 'modify_date'


class PostYAV(YearArchiveView):
    model = Post
    date_field = 'modify_date'
    make_object_list = True


class PostMAV(MonthArchiveView):
    model = Post
    date_field = 'modify_date'


class PostDAV(DayArchiveView):
    model = Post
    date_field = 'modify_date'


class PostTAV(TodayArchiveView):
    model = Post
    date_field = 'modify_date'

blog/bookmark/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView

from .models import Bookmark
# Create your views here.

class BookmarkLV(ListView):
    model = Bookmark

class BookmarkDV(DetailView):
    model = Bookmark

blog/homepage/views.py
from django.views import generic
from django.shortcuts import render, reverse

from .models import Board

# Create your views here.

# object_list = Board.objects.order_by('-published_date')[:10]

"""
def index(request):
    # object_list = Board.objects.order_by('-published_date')[:5]
    # template = loader.get_template('homepage/index.html')
    #
    # return HttpResponse(template.render({'board_title': object_list}, request))

    object_list = Board.objects.order_by('-published_date')[:10]

    context = {
        'object_list': object_list,
        'object_len': int(Board.objects.count() / 10 + 1)
    }
    
    return render(request, 'homepage/index.html', context)
"""


# ListView 의 Default value 1) context_object_name = object_list
# 2) template_name = 모델명 소문자_detail.html
class IndexView(generic.ListView):
    model = Board
    template_name = 'homepage/index.html'
    paginate_by = 5  # 한 페이지에 보여줄 오브젝트 갯수
    # pagination 을 할 땐, template에서 page_obj 인스턴스의 메소드가 사용가능
    # is_paginated 페이징 됐다면
    # has_previous = 이전 페이지가 있다면
    # paginator.page_range = 페이지 갯수




# DetailView 의 Default value 1) context_object_name = object
# 2) template_name = 모델명 소문자_detail.html
class DetailView(generic.DetailView):
    model = Board
    template_name = 'homepage/detail.html'


# def detail(request, board_id):
#     post = go4(Board, pk=board_id)
#     return render(request, 'homepage/detail.html', {'post': post})

def check_boardnum(request):
    num = request.POST.get('pk',None)

    return reverse('homepage:detail', kwargs={'pk': 1})

blog/blog2/templates/blog2/post_all.html
{% extends 'base.html' %}

{% block aside %}
<aside>
    BlogList
</aside>
{% endblock %}

{% block content %}
<nav>
    {% if posts %}
    <ul id="content_list">
        {% for post in posts %}
        <li class="item_list" onclick="location.href = '{{ post.get_absolute_url }}'">
            <p class="item_title" >{{ post.title }}</p>
            <p class="item_time">{{ post.modify_date|date:"N d, Y" }}</p>
            <p class="item_content">{{ post.description }}</p>

            <!-- N d, Y 형식으로 filtering 하면 July 18, 2018 같은 식으로 출력
             get_absolute_url 은 모델 클래스의 메소드로 정의되어 있어야하며
             코드가 간략해지는 장점이 있음-->

        </li>
        {% endfor %}

        {% if is_paginated %}
        <ul id="page_list">
            {% if page_obj.has_previous%}
            <li><a href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
            {% else %}
            <li class="disabled">&laquo;</li>
            {% endif %}
            {% for i in paginator.page_range %}
            {% if page_obj.number == i %}
            <li class="active"><p>{{ i }}</p></li>
            {% else %}
            <li><a href="?page={{ i }}">{{ i }}</a></li>
            {% endif %}
            {% endfor %}
            <!--page_obj 는 장고의 Page 객체가 들어있는 context 변수
            page_obj.number 는 현재 페이지 번호, page_obj.paginator.num_pages는 총 페이지 개수-->
            {% if page_obj.has_next %}
            <li><a href="?page={{ page_obj.next_page_number}}">&raquo;</a></li>
            {% else %}
            <li class="disabled">&raquo;</li>
            {% endif %}
        </ul>
        {% endif %}
    </ul>

        {% else %}
    <p>No Have Posts's Objects!</p>
    {% endif %}
    </ul>


</nav>
{% endblock %}

blog/blog2/templates/blog2/post_archive.html
<h1>Post Archives untill {% now "N d, Y %}</h1>
<ul>
    {% for date in date_list %}
    <li style="display: inline;">
        <a href="{% url 'blog2:post_year_archive' date|date:'Y' %}">Year-{{ date|date:"Y" }}</a>
    </li>
    {% endfor %}
</ul>
<br/>

<div>
    <ul>
        {% for post in object_list %}
        <li>{{ post.modify_date|date:"Y-m-d" }}&nbsp;&nbsp;&nbsp;
            <a href="{{ post.get_absolute_url }} "><strong>{{ post.title }}</strong></a></li>
        {% endfor %}
    </ul>
</div>

blog/blog2/templates/blog2/post_archive_day.html
<h1>Post Archives for {{ month|date:"N d, Y" }}</h1>
<!-- July 19, 2018 형식-->

<div>
    <ul>
        {% for post in object_list %}
        <li>{{ post.modify_date|date:"Y-m-d" }}&nbsp;&nbsp;&nbsp;
            <a href="{{ post.get_absolute_url }}"><strong>{{ post.title }}</strong></a></li>
        {% endfor %}
    </ul>
</div>

blog/blog2/templates/blog2/post_archive_month.html
<h1>Post Archives for {{ month|date:"N, Y" }}</h1>
<!-- July 2018 형식-->


<div>
    <ul>
        {% for post in object_list %}
        <li>{{ post.modify_date|date:"Y-m-d" }}&nbsp;&nbsp;&nbsp;
            <a href="{{ post.get_absolute_url }}"><strong>{{ post.title }}</strong></a></li>
        {% endfor %}
    </ul>
</div>

blog/blog2/templates/blog2/post_archive_year.html
<h1>Post Archives for {{ year|date:"Y" }}</h1>

<ul style="background-color: aliceblue;">
    {% for date in date_list %}
    <li style="display: inline;">
        <a href="{% url 'blog2:post_month_archive' year|date:'Y' date|date:'b' %}">
            {{ date|date:"F" }}</a>
    </li>
    {% endfor %}
</ul>
<br/>

<div>
    <ul>
        {% for post in object_list %}
        <li>{{ post.modify_date|date:"Y-m-d" }}&nbsp;&nbsp;&nbsp;
            <a href="{{ post.get_absolute_url }}"><strong>{{ post.title }}</strong></a></li>
        {% endfor %}
    </ul>
</div>

blog/blog2/templates/blog2/post_detail.html
<h2>{{ object.title }}</h2>

<p class="other_posts">
    {% if object.get_previous_in_order %}
    <a href="{{ object.get_previous_post.get_absolute_url }}" title="View previous post">
        &laquo;--{{ object.get_previous_post }}</a>
    {% endif %}

    {% if object.get_next_in_order %}
    ||<a href="{{ object.get_next_post.get_absolute_url }}" title="View next post">{{ objct.get_next_post}}</a>
    {% endif %}
</p>

<p class="date">{{ object.modify_date|date:"Y F j" }}</p>
<!-- 2018, 7월 19 로 출력 -->
<div class="body">
    {{ object.content|linebreaks }}
    <!-- linebreaks 를 통해서 /newline 을 인식할 수 있음 -->
</div>

blog/bookmark/templates/bookmark/bookmark_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Django Bookmark Detail</title>
</head>
<body>
    <div id="content">
        <h1>Naver Homepage</h1>
        <hr>
        <ul>
            <li>URL: <a href="{{ object.url }}">{{ object.url}}</a> </li>
        </ul>
    </div>
</body>
</html>

blog/bookmark/templates/bookmark/bookmark_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Django Bookmark List</title>
</head>
<body>
    <div id="content">
        <h1>Bookmark List</h1>
        <hr>
        <ul>
            {% for bookmark in object_list %}
                <li><a href="{% url 'detail' bookmark.id %}">{{ bookmark }} </a></li>
            {% endfor %}
        </ul>
    </div>
</body>
</html>

blog/homepage/templates/homepage/detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
            <link rel="stylesheet" type="text/css" href="{% static 'homepage/detail_style.css' %}" />
            <content>
                <h1>{{ object.title }}</h1>
                <p>{{ object.created_date|date:"Y년 M d일 h:i" }}</p>
                <hr>
                <article>
                    <div>{{ object.text }}</div>
                </article>
            </content>
{% endblock %}

blog/homepage/templates/homepage/index.html
{% extends 'base.html' %}

{% block javascript %}
<script>
    $(".item_list").click(function () {
        var num = parseInt(this.id);

        $.ajax({});
    });
</script>
{% endblock %}

{% block aside%}
<aside>
    Post List
</aside>
{% endblock %}

{% block content %}
<nav>
    {% if object_list %}
    <ul id="content_list">
        {% for row in object_list %}

        <li class="item_list" id="{{ row.id }}" onclick="location.href = '{{ row.get_absolute_url }}'">
        <!--<li class="item_list" id="{{ row.id }}">-->
        <p class="item_title">{{ row.title }}</p>
        <p class="item_time">{{ row.created_date|date:"Y년 M d일 h:i" }}</p>
        <p class="item_content">{{ row.text|truncatewords:50 }}</p>
        </li>
        {% endfor %}

        {% if is_paginated %}
        <ul id="page_list">
            {% if page_obj.has_previous %}
            <li><a href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
            {% else %}
            <li class="disabled">&laquo;</li>
            {% endif %}
            {% for i in paginator.page_range %}
            {% if page_obj.number == i %}
            <li class="active"><p>{{ i }}</p></li>
            {% else %}
            <li><a href="?page={{ i }}">{{ i }}</a></li>
            {% endif %}
            {% endfor %}
            {% if page_obj.has_next %}
            <li><a href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
            {% else %}
            <li class="disabled">&raquo;</li>
            {% endif %}
        </ul>
        {% endif %}
    </ul>


    {% else %}
    <p> No Have Board's Objects! </p>
    {% endif %}
</nav>


{% endblock %}

blog/templates/base.html
{% load static %}
<html>

<head>
    <meta charset="UTF-8">
    <title>SUJAE'S BLOG</title>
    <!-- BOOT STRAP -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'homepage/style.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'css/animations.css' %}"/>
</head>
<body>

<header class="header-down">
    <nav>
        <ul id="header_ul">
            <li id="home_but"><a href="/"> Sujae's Blog</a></li>
            <li><a href="/practice/"> first</a></li>
            <li><a href=""> second</a></li>
            <li><a href=""> third</a></li>
            <li><a href=""> fourth</a></li>
        </ul>
    </nav>
</header>


<section>
    {% block aside %}
    <aside>aside</aside>
    {% endblock %}

    {% block content %}
    {% endblock %}
</section>

<footer>
    footer
</footer>

<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js"
        integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh"
        crossorigin="anonymous"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/animation.js' %}"></script>

{% block javascript %}{% endblock %}
</body>
</html>

blog/templates/homepage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>


</body>
</html>